apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: arminahari/devops-demo:821ec87ead359de50e5d9b7ee2e790af4d161e0d
        ports:
        - containerPort: 5000
